# Generated by Django 5.0.6 on 2024-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
