# Generated by Django 5.0.6 on 2024-06-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0004_profile_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='invitation_code',
            field=models.CharField(default=43553342, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
