# Generated by Django 5.0.6 on 2024-06-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0007_alter_family_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='app_family_finance.profile')),
            ],
        ),
    ]
