# Generated by Django 5.0.6 on 2024-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0008_alter_profile_parent_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
