# Generated by Django 5.0.6 on 2024-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0014_alter_responsibility_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='allowance_period',
            field=models.IntegerField(default=14),
        ),
    ]
