# Generated by Django 5.0.6 on 2024-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0015_family_allowance_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='allowance_period',
        ),
        migrations.AddField(
            model_name='family',
            name='allowance_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='family',
            name='allowance_period_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_money',
            field=models.IntegerField(default=0),
        ),
    ]
