# Generated by Django 5.0.6 on 2024-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0016_remove_family_allowance_period_family_allowance_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='allowance_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='family',
            name='allowance_period_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Daily', 'Daily')], default='Daily', max_length=10),
        ),
    ]
