# Generated by Django 5.0.6 on 2024-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0017_alter_family_allowance_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='last_allowance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
