# Generated by Django 5.0.6 on 2024-06-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0018_family_last_allowance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='allowance_period_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=10),
        ),
    ]
