# Generated by Django 5.0.6 on 2024-06-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0019_alter_family_allowance_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='price_per_difficulty_point',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
