# Generated by Django 5.0.6 on 2024-06-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0020_family_price_per_difficulty_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Too Easy'), (1, 'Super Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard'), (6, 'Extreme')], default=0),
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='app_family_finance.family')),
            ],
        ),
    ]
