# Generated by Django 5.0.6 on 2024-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0021_alter_responsibility_difficulty_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
