# Generated by Django 5.0.6 on 2024-06-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0023_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='allowance_period_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=10),
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('investment', 'Investment'), ('loan', 'Loan')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='app_family_finance.family')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returns', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app_family_finance.profile')),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app_family_finance.financialaccount')),
            ],
        ),
    ]
