# Generated by Django 5.0.6 on 2024-06-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0024_alter_family_allowance_period_type_financialaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccount',
            name='balance',
        ),
    ]
