# Generated by Django 5.0.6 on 2024-06-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0026_financialaccount_interest_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='last_interest_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
