# Generated by Django 5.0.6 on 2024-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0027_financialaccount_last_interest_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='repeat',
            field=models.TextField(default='{}'),
        ),
    ]
