# Generated by Django 5.0.6 on 2024-06-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0028_responsibility_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='repeat',
        ),
    ]
