# Generated by Django 5.0.6 on 2024-06-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0029_remove_responsibility_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilitySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('repeat_type', models.CharField(max_length=10)),
                ('repeat_days', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='responsibility',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='app_family_finance.responsibilityseries'),
        ),
    ]
