# Generated by Django 5.0.6 on 2024-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0030_responsibilityseries_responsibility_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='single',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
