# Generated by Django 5.0.6 on 2024-06-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_family_finance', '0032_alter_family_price_per_difficulty_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='price_per_difficulty_point',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4),
        ),
    ]
